import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core'

export const articles = pgTable('articles', {
  id: uuid('id').defaultRandom().primaryKey(),
  slug: varchar('slug', { length: 220 }).notNull().unique(),
  title: text('title').notNull(),
  englishTitle: text('english_title'),
  summary: text('summary'),
  body: text('body').notNull(),
  category: varchar('category', { length: 80 }).notNull(),
  state: varchar('state', { length: 80 }),
  district: varchar('district', { length: 120 }),
  status: varchar('status', { length: 40 }).notNull().default('draft'),
  authorId: varchar('author_id', { length: 160 }).notNull(),
  reviewerId: varchar('reviewer_id', { length: 160 }),
  publisherId: varchar('publisher_id', { length: 160 }),
  imageUrl: text('image_url'),
  thumbnailUrl: text('thumbnail_url'),
  imageAlt: text('image_alt'),
  media: jsonb('media').$type<Array<Record<string, unknown>>>().notNull().default([]),
  tags: jsonb('tags').$type<string[]>().notNull().default([]),
  isBreaking: boolean('is_breaking').notNull().default(false),
  isTopStory: boolean('is_top_story').notNull().default(false),
  isTrending: boolean('is_trending').notNull().default(false),
  isEditorsPick: boolean('is_editors_pick').notNull().default(false),
  isTodaysEdition: boolean('is_todays_edition').notNull().default(false),
  views: integer('views').notNull().default(0),
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [
  index('articles_latest_idx').on(table.status, table.publishedAt),
  index('articles_category_idx').on(table.category, table.publishedAt),
  index('articles_location_idx').on(table.state, table.district, table.publishedAt),
])

export const articleWorkflow = pgTable('article_workflow', {
  id: uuid('id').defaultRandom().primaryKey(),
  articleId: uuid('article_id').notNull().references(() => articles.id, { onDelete: 'cascade' }),
  fromStatus: varchar('from_status', { length: 40 }),
  toStatus: varchar('to_status', { length: 40 }).notNull(),
  action: varchar('action', { length: 120 }).notNull(),
  comments: text('comments'),
  actorId: varchar('actor_id', { length: 160 }).notNull(),
  actorRole: varchar('actor_role', { length: 40 }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [index('article_workflow_article_idx').on(table.articleId, table.createdAt)])
